name: Build IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      PROJECT: GymFlow.xcodeproj
      SCHEME: GymFlow
      CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v4

      - name: Debug
        run: |
          pwd
          ls -la
          find . -name "*.xcodeproj"
          find . -name "project.pbxproj"

      - name: Build
        run: |
          xcodebuild \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            build

      - name: Create IPA
        run: |
          mkdir Payload

          APP=$(find build/Build/Products/Release-iphoneos -name "*.app" | head -n1)

          cp -R "$APP" Payload/

          zip -r Gymflow.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: Gymflow.ipa
